//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public makale()
        {
            this.resim = new HashSet<resim>();
        }
    
        public int id { get; set; }
        public string baslik { get; set; }
        public string makale1 { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> yazar_id { get; set; }
        public Nullable<int> kategori_id { get; set; }
    
        public virtual yazar yazar { get; set; }
        public virtual kategori kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<resim> resim { get; set; }
    }
}
