//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resim
    {
        public int id { get; set; }
        public string resim_yol { get; set; }
        public Nullable<int> yazi_id { get; set; }
        public string varsayilan { get; set; }
    
        public virtual makale makale { get; set; }
    }
}
